version: '3'
services:
    telegraf:
      image: telegraf:1.19
      volumes:
        - ./mytelegraf.conf:/etc/telegraf/telegraf.conf
        - /proc:/hostfs/proc:ro
      env_file:
        - ./telegraf.env
      environment: 
        - HOST_PROC=/hostfs/proc
      restart: unless-stopped
